version: '3.7'
services:
  fastapi:
    build: ./fastapi
    volumes:
      - ./fastapi:/src
    ports:
      - 8000:8000
    environment:
      DB_NAME: barifac
      DB_USER: fastapi
      DB_PASSWORD: fastapi
      DB_HOST: postgres
      DB_PORT: 5433
    links:
      - postgres
  postgres:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: fastapi
      POSTGRES_DB: barifac
    ports:
      - 5433:5432

volumes:
  postgres_data:
