from .attend_subject import AttendSubjectAPI
from .department import DepartmentAPI
from .evaluation import EvaluationAPI
from .school import SchoolAPI
from .score import ScoreAPI
from .subject import SubjectAPI
from .teacher import TeacherAPI
from .teacher_comment import TeacherCommentAPI
from .term import TermAPI
from .user import UserAPI
