from .attend_subject import AttendSubjectCRUD
from .base import BaseCRUD
from .department import DepartmentCRUD
from .evaluation import EvaluationCRUD
from .school import SchoolCRUD
from .score import ScoreCRUD
from .subject import SubjectCRUD
from .subject_comment import SubjectCommentCRUD
from .teacher import TeacherCRUD
from .teacher_comment import TeacherCommentCRUD
from .term import TermCRUD
from .user import UserCRUD
