from .attend_subject import AttendSubjectCRUD
from .base import BaseCRUD
from .department import DepartmentCRUD
from .evaluation import EvaluationCRUD
from .school import SchoolCRUD
from .score import ScoreCRUD
from .subject import SubjectCRUD
from .teacher import TeacherCRUD
from .term import TermCRUD
from .user import UserCRUD
