"""add_ondelete

Revision ID: 8c0541cd14bc
Revises: b26a53bb453c
Create Date: 2021-12-13 01:40:42.242518+09:00

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "8c0541cd14bc"
down_revision = "b26a53bb453c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "attend_subjects_subject_uuid_fkey", "attend_subjects", type_="foreignkey"
    )
    op.drop_constraint(
        "attend_subjects_user_uuid_fkey", "attend_subjects", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "attend_subjects",
        "subjects",
        ["subject_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "attend_subjects", "users", ["user_uuid"], ["uuid"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "departments_school_uuid_fkey", "departments", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "departments", "schools", ["school_uuid"], ["uuid"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "evaluations_subject_uuid_fkey", "evaluations", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "evaluations", "subjects", ["subject_uuid"], ["uuid"], ondelete="CASCADE"
    )
    op.drop_constraint("scores_evaluation_uuid_fkey", "scores", type_="foreignkey")
    op.create_foreign_key(
        None, "scores", "evaluations", ["evaluation_uuid"], ["uuid"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "subject_comments_user_uuid_fkey", "subject_comments", type_="foreignkey"
    )
    op.drop_constraint(
        "subject_comments_subject_uuid_fkey", "subject_comments", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "subject_comments",
        "subjects",
        ["subject_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "subject_comments", "users", ["user_uuid"], ["uuid"], ondelete="CASCADE"
    )
    op.drop_constraint("subjects_school_uuid_fkey", "subjects", type_="foreignkey")
    op.drop_constraint("subjects_teacher_uuid_fkey", "subjects", type_="foreignkey")
    op.drop_constraint("subjects_term_uuid_fkey", "subjects", type_="foreignkey")
    op.create_foreign_key(
        None, "subjects", "teachers", ["teacher_uuid"], ["uuid"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "subjects", "schools", ["school_uuid"], ["uuid"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "subjects", "terms", ["term_uuid"], ["uuid"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "teacher_comments_user_uuid_fkey", "teacher_comments", type_="foreignkey"
    )
    op.drop_constraint(
        "teacher_comments_teacher_uuid_fkey", "teacher_comments", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "teacher_comments",
        "teachers",
        ["teacher_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "teacher_comments", "users", ["user_uuid"], ["uuid"], ondelete="CASCADE"
    )
    op.drop_constraint("teachers_school_uuid_fkey", "teachers", type_="foreignkey")
    op.create_foreign_key(
        None, "teachers", "schools", ["school_uuid"], ["uuid"], ondelete="CASCADE"
    )
    op.drop_constraint("users_department_uuid_fkey", "users", type_="foreignkey")
    op.drop_constraint("users_school_uuid_fkey", "users", type_="foreignkey")
    op.create_foreign_key(
        None, "users", "departments", ["department_uuid"], ["uuid"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "users", "schools", ["school_uuid"], ["uuid"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        "users_school_uuid_fkey", "users", "schools", ["school_uuid"], ["uuid"]
    )
    op.create_foreign_key(
        "users_department_uuid_fkey",
        "users",
        "departments",
        ["department_uuid"],
        ["uuid"],
    )
    op.drop_constraint(None, "teachers", type_="foreignkey")
    op.create_foreign_key(
        "teachers_school_uuid_fkey", "teachers", "schools", ["school_uuid"], ["uuid"]
    )
    op.drop_constraint(None, "teacher_comments", type_="foreignkey")
    op.drop_constraint(None, "teacher_comments", type_="foreignkey")
    op.create_foreign_key(
        "teacher_comments_teacher_uuid_fkey",
        "teacher_comments",
        "teachers",
        ["teacher_uuid"],
        ["uuid"],
    )
    op.create_foreign_key(
        "teacher_comments_user_uuid_fkey",
        "teacher_comments",
        "users",
        ["user_uuid"],
        ["uuid"],
    )
    op.drop_constraint(None, "subjects", type_="foreignkey")
    op.drop_constraint(None, "subjects", type_="foreignkey")
    op.drop_constraint(None, "subjects", type_="foreignkey")
    op.create_foreign_key(
        "subjects_term_uuid_fkey", "subjects", "terms", ["term_uuid"], ["uuid"]
    )
    op.create_foreign_key(
        "subjects_teacher_uuid_fkey", "subjects", "teachers", ["teacher_uuid"], ["uuid"]
    )
    op.create_foreign_key(
        "subjects_school_uuid_fkey", "subjects", "schools", ["school_uuid"], ["uuid"]
    )
    op.drop_constraint(None, "subject_comments", type_="foreignkey")
    op.drop_constraint(None, "subject_comments", type_="foreignkey")
    op.create_foreign_key(
        "subject_comments_subject_uuid_fkey",
        "subject_comments",
        "subjects",
        ["subject_uuid"],
        ["uuid"],
    )
    op.create_foreign_key(
        "subject_comments_user_uuid_fkey",
        "subject_comments",
        "users",
        ["user_uuid"],
        ["uuid"],
    )
    op.drop_constraint(None, "scores", type_="foreignkey")
    op.create_foreign_key(
        "scores_evaluation_uuid_fkey",
        "scores",
        "evaluations",
        ["evaluation_uuid"],
        ["uuid"],
    )
    op.drop_constraint(None, "evaluations", type_="foreignkey")
    op.create_foreign_key(
        "evaluations_subject_uuid_fkey",
        "evaluations",
        "subjects",
        ["subject_uuid"],
        ["uuid"],
    )
    op.drop_constraint(None, "departments", type_="foreignkey")
    op.create_foreign_key(
        "departments_school_uuid_fkey",
        "departments",
        "schools",
        ["school_uuid"],
        ["uuid"],
    )
    op.drop_constraint(None, "attend_subjects", type_="foreignkey")
    op.drop_constraint(None, "attend_subjects", type_="foreignkey")
    op.create_foreign_key(
        "attend_subjects_user_uuid_fkey",
        "attend_subjects",
        "users",
        ["user_uuid"],
        ["uuid"],
    )
    op.create_foreign_key(
        "attend_subjects_subject_uuid_fkey",
        "attend_subjects",
        "subjects",
        ["subject_uuid"],
        ["uuid"],
    )
    # ### end Alembic commands ###
