"""edit_request

Revision ID: e8da8b438a8c
Revises: 8849661f935f
Create Date: 2021-12-17 00:44:30.219744+09:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e8da8b438a8c"
down_revision = "8849661f935f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "edit_requests",
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="登録日時",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            comment="最終更新日時",
        ),
        sa.Column("is_active", sa.BOOLEAN(), server_default="true", nullable=False),
        sa.Column("user_uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("comment", sa.VARCHAR(length=2000), nullable=False),
        sa.Column("subject_uuid", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("evaluation_uuid", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["evaluation_uuid"], ["evaluations.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["subject_uuid"], ["subjects.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_uuid"], ["users.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("edit_requests")
    # ### end Alembic commands ###
