"""subject

Revision ID: e3d4dbe0fe8c
Revises: cce83fc74b50
Create Date: 2021-12-05 23:01:00.056136+09:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e3d4dbe0fe8c"
down_revision = "cce83fc74b50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subjects",
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="登録日時",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            comment="最終更新日時",
        ),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("school_uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("term_uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("teacher_uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_uuid"],
            ["schools.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_uuid"],
            ["teachers.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["term_uuid"],
            ["terms.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name", "school_uuid", "term_uuid", "teacher_uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subjects")
    # ### end Alembic commands ###
