"""attend_subjects

Revision ID: d54a1cb702d8
Revises: aec7a6411b64
Create Date: 2021-12-06 11:42:33.399036+09:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d54a1cb702d8"
down_revision = "aec7a6411b64"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attend_subjects",
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="登録日時",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            comment="最終更新日時",
        ),
        sa.Column("user_uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("subject_uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("target_value", sa.VARCHAR(length=1), nullable=False),
        sa.Column("target_score", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_uuid"],
            ["subjects.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("user_uuid", "subject_uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attend_subjects")
    # ### end Alembic commands ###
