"""update_user

Revision ID: d2ff912e28ca
Revises: fdc59e683302
Create Date: 2021-12-06 19:49:58.454629+09:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d2ff912e28ca"
down_revision = "fdc59e683302"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("school_uuid", postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("department_uuid", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(None, "users", "departments", ["department_uuid"], ["uuid"])
    op.create_foreign_key(None, "users", "schools", ["school_uuid"], ["uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "department_uuid")
    op.drop_column("users", "school_uuid")
    # ### end Alembic commands ###
