"""username_unique

Revision ID: 76731fd09584
Revises: 12e9d4f30b77
Create Date: 2021-12-18 14:07:52.152398+09:00

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "76731fd09584"
down_revision = "12e9d4f30b77"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_username_key", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("users_username_key", "users", ["username"])
    # ### end Alembic commands ###
