"""syllabus_info

Revision ID: 65364488da0f
Revises: 7e03f3f5f6a7
Create Date: 2021-12-14 19:18:06.403341+09:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "65364488da0f"
down_revision = "7e03f3f5f6a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "departments", sa.Column("syllabus_url", sa.VARCHAR(length=1024), nullable=True)
    )
    op.add_column(
        "schools", sa.Column("syllabus_url", sa.VARCHAR(length=1024), nullable=True)
    )
    op.add_column(
        "subjects", sa.Column("category", sa.VARCHAR(length=10), nullable=True)
    )
    op.add_column("subjects", sa.Column("type", sa.VARCHAR(length=10), nullable=True))
    op.add_column("subjects", sa.Column("target_grade", sa.Integer(), nullable=True))
    op.add_column(
        "subjects",
        sa.Column("target_department", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.add_column(
        "subjects", sa.Column("syllabus_url", sa.VARCHAR(length=1024), nullable=True)
    )
    op.create_foreign_key(
        None,
        "subjects",
        "departments",
        ["target_department"],
        ["uuid"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subjects", type_="foreignkey")
    op.drop_column("subjects", "syllabus_url")
    op.drop_column("subjects", "target_department")
    op.drop_column("subjects", "target_grade")
    op.drop_column("subjects", "type")
    op.drop_column("subjects", "category")
    op.drop_column("schools", "syllabus_url")
    op.drop_column("departments", "syllabus_url")
    # ### end Alembic commands ###
