"""grade_nullable_true

Revision ID: 20baa426751c
Revises: 1595a2312b55
Create Date: 2021-12-12 19:36:12.876464+09:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20baa426751c"
down_revision = "1595a2312b55"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "grade", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "grade", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
