"""is_active

Revision ID: 8849661f935f
Revises: 456cc0a718b1
Create Date: 2021-12-16 17:21:35.393591+09:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8849661f935f"
down_revision = "456cc0a718b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attend_subjects",
        sa.Column("is_active", sa.BOOLEAN(), server_default="true", nullable=False),
    )
    op.add_column(
        "departments",
        sa.Column("is_active", sa.BOOLEAN(), server_default="true", nullable=False),
    )
    op.add_column(
        "evaluations",
        sa.Column("is_active", sa.BOOLEAN(), server_default="true", nullable=False),
    )
    op.add_column(
        "schools",
        sa.Column("is_active", sa.BOOLEAN(), server_default="true", nullable=False),
    )
    op.add_column(
        "scores",
        sa.Column("is_active", sa.BOOLEAN(), server_default="true", nullable=False),
    )
    op.add_column(
        "subject_comments",
        sa.Column("is_active", sa.BOOLEAN(), server_default="true", nullable=False),
    )
    op.add_column(
        "subjects",
        sa.Column("is_active", sa.BOOLEAN(), server_default="true", nullable=False),
    )
    op.add_column(
        "teacher_comments",
        sa.Column("is_active", sa.BOOLEAN(), server_default="true", nullable=False),
    )
    op.add_column(
        "teachers",
        sa.Column("is_active", sa.BOOLEAN(), server_default="true", nullable=False),
    )
    op.add_column(
        "terms",
        sa.Column("is_active", sa.BOOLEAN(), server_default="true", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("terms", "is_active")
    op.drop_column("teachers", "is_active")
    op.drop_column("teacher_comments", "is_active")
    op.drop_column("subjects", "is_active")
    op.drop_column("subject_comments", "is_active")
    op.drop_column("scores", "is_active")
    op.drop_column("schools", "is_active")
    op.drop_column("evaluations", "is_active")
    op.drop_column("departments", "is_active")
    op.drop_column("attend_subjects", "is_active")
    # ### end Alembic commands ###
