"""score

Revision ID: 439129fe7774
Revises: d2ff912e28ca
Create Date: 2021-12-06 19:56:00.985175+09:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "439129fe7774"
down_revision = "d2ff912e28ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scores",
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="登録日時",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            comment="最終更新日時",
        ),
        sa.Column("attend_subject_uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("evaluation_uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("got_score", sa.Integer(), nullable=False),
        sa.Column("max_score", sa.Integer(), nullable=False),
        sa.Column("memo", sa.VARCHAR(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["attend_subject_uuid"],
            ["attend_subjects.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_uuid"],
            ["evaluations.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scores")
    # ### end Alembic commands ###
