"""subject_category_type_length

Revision ID: 12e9d4f30b77
Revises: 34f10216ac86
Create Date: 2021-12-18 02:55:28.752035+09:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "12e9d4f30b77"
down_revision = "34f10216ac86"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subjects",
        "category",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "subjects",
        "type",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subjects",
        "type",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
    )
    op.alter_column(
        "subjects",
        "category",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
