"""fix_target_department_uuid

Revision ID: 04be7ef14f1a
Revises: 65364488da0f
Create Date: 2021-12-14 21:20:46.818024+09:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "04be7ef14f1a"
down_revision = "65364488da0f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subjects",
        sa.Column(
            "target_department_uuid", postgresql.UUID(as_uuid=True), nullable=True
        ),
    )
    op.drop_constraint(
        "subjects_target_department_fkey", "subjects", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "subjects",
        "departments",
        ["target_department_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_column("subjects", "target_department")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subjects",
        sa.Column(
            "target_department", postgresql.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "subjects", type_="foreignkey")
    op.create_foreign_key(
        "subjects_target_department_fkey",
        "subjects",
        "departments",
        ["target_department"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_column("subjects", "target_department_uuid")
    # ### end Alembic commands ###
