"""update score

Revision ID: b26a53bb453c
Revises: 1595a2312b55
Create Date: 2021-12-12 21:01:42.335838+09:00

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "b26a53bb453c"
down_revision = "1595a2312b55"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("scores_attend_subject_uuid_fkey", "scores", type_="foreignkey")
    op.create_foreign_key(
        None,
        "scores",
        "attend_subjects",
        ["attend_subject_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "scores", type_="foreignkey")
    op.create_foreign_key(
        "scores_attend_subject_uuid_fkey",
        "scores",
        "attend_subjects",
        ["attend_subject_uuid"],
        ["uuid"],
    )
    # ### end Alembic commands ###
