name: docker

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build & Up
        run: docker-compose up -d
      - name: Poetry install [fastapi]
        run: docker-compose run fastapi poetry install
      - name: DB migrate [fastapi]
        run: docker-compose run fastapi poetry run alembic upgrade head
